--create database DML;

--use DML;

--1. CREATE TABLE MY_EMPLOYEE (
--    ID INT NOT NULL,
--    LAST_NAME VARCHAR(25),
--    FIRST_NAME VARCHAR(25),
--    USERID VARCHAR(8),
--    SALARY DECIMAL(9,2),
--    PRIMARY KEY (ID)
--);


--SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'MY_EMPLOYEE';

--2. INSERT INTO MY_EMPLOYEE 
--VALUES (1, 'Patel', 'Ralph', 'rpatel', 895);

--3. INSERT INTO MY_EMPLOYEE (ID, LAST_NAME, FIRST_NAME, USERID, SALARY) 
--VALUES (2, 'Dancs', 'Betty', 'bdancs', 860);

--4. SELECT * FROM MY_EMPLOYEE;

--5. DECLARE @ID INT, @LAST_NAME VARCHAR(25), @FIRST_NAME VARCHAR(25), @SALARY DECIMAL(9,2);

--SET @ID = 3;
--SET @LAST_NAME = 'Smith';
--SET @FIRST_NAME = 'John';
--SET @SALARY = 950;

--INSERT INTO MY_EMPLOYEE (ID, LAST_NAME, FIRST_NAME, USERID, SALARY) 
--VALUES (@ID, @LAST_NAME, @FIRST_NAME, 
--        LOWER(LEFT(@FIRST_NAME,1) + LEFT(@LAST_NAME,7)), 
--        @SALARY);

--6. UPDATE MY_EMPLOYEE 
--SET LAST_NAME = 'Drexler' 
--WHERE ID = 3;

--7. UPDATE MY_EMPLOYEE 
--SET SALARY = 1000 
--WHERE SALARY < 900;

--8. DELETE FROM MY_EMPLOYEE 
--WHERE LAST_NAME = 'Dancs' AND FIRST_NAME = 'Betty';

--9. TRUNCATE TABLE MY_EMPLOYEE;
